# tag::common[]
name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
# end::common[]
# tag::setupnode[]
      - uses: actions/setup-node@v3
        with:
          node-version: 19
# end::setupnode[]
#tag::initial[]
      - run: npm install
      - run: npm run lint
#end::initial[]
